# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 14:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelGradute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Краткое описание')),
                ('task_text', ckeditor.fields.RichTextField(verbose_name='Описание задания')),
                ('when_created', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('when_updated', models.DateTimeField(auto_now=True, verbose_name='Когда обновлено')),
                ('difficult_level', models.IntegerField(choices=[[1, 'Простой уровень'], [2, 'Средний уровень'], [3, 'Сложный уровень'], [4, 'Олимпиадный уровень']], verbose_name='Уровень сложности')),
                ('level_grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grad_tasks', to='tasks.LevelGradute', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tasks', to='tasks.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-when_created'],
                'get_latest_by': '-when_created',
            },
        ),
    ]
