# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170425_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
