# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 20:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ответ на задание'),
        ),
    ]
